# ROS Console Debug Configuration
log4j.logger.ros.gmapping=DEBUG
log4j.logger.ros.gmapping.message_filter=DEBUG
log4j.logger.ros.gmapping.slam_gmapping=DEBUG
log4j.logger.ros.tf=DEBUG
log4j.logger.ros.tf2=DEBUG

